name: BATS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  bash-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GNU parallel
        run: |
          sudo apt-get update
          sudo apt-get install -y parallel

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install BATS via NPM
        run: npm install -g bats

      - name: Verify BATS installation
        run: bats --version

      - name: Run Docker Tests (Bash)
        env:
          ENV_SYNC_SKIP_GO_BUILD: "true"
          ENV_SYNC_USE_BASH: "true"
          ENV_SYNC_GO_BIN: legacy/bin/env-sync
        run: ./test-dockers.sh --skip-go-build --debug
  go-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install BATS
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          cd ..
          rm -rf bats-core

      - name: Verify BATS installation
        run: bats --version

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Go Tests
        run: make test

      - name: Run Docker Tests (Go)
        run: ./test-dockers.sh --debug
